apiVersion: apps/v1

kind: Deployment

metadata:

  name: model-training

spec:

  replicas: 10

  selector:

    matchLabels:

      app: model-training

  template:

    metadata:

      labels:

        app: model-training

    spec:

      containers:

      - name: model-training-container

        image: chelyn/modeltraining:latest

        volumeMounts:

        - name: shared-volume

          mountPath: /data

      volumes:

      - name: shared-storage
        
        persistentVolumeClaim:
    
            claimName: shared-pvc
