apiVersion: apps/v1

kind: Deployment

metadata:

  name: model-training

spec:

  replicas: 1

  selector:

    matchLabels:

      app: model-training

  template:

    metadata:

      labels:

        app: model-training

    spec:

      containers:

      - name: model-training-container

        image: chelyn/modeltraining:latest

        volumeMounts:

        - name: shared-pv

          mountPath: /mnt/data

      volumes:

      - name: shared-pv

        persistentVolumeClaim:

          claimName: shared-pvc
