apiVersion: v1

kind: Pod

metadata:

  name: model-training-pod

  labels:
    zone: prod

    version: v1

spec:

  containers:

  - name: model-training-container

    image: chelyn/modeltraining

    ports:

    - containerPort: 8080  

    volumeMounts:

    - name: shared-volume
    
    mountPath: /data

  volumes:

  - name: shared-volume

    emptyDir: {}