apiVersion: v1

kind: PersistentVolumeClaim

metadata:

    name: shared-pvc

spec:

    storageClassName: dynamic-storage
    
    accessModes:

        - ReadWriteMany

    resources:
   
        requests:
  
            storage: 20Gi
