apiVersion: apps/v1

kind: Deployment

metadata:

  name: data-processing

spec:

  replicas: 3

  selector:

    matchLabels:

      app: data-processing

  template:

    metadata:

      labels:

        app: data-processing

    spec:

      containers:

      - name: data-processing-container

        image: rhiann/dataprocessing:latest

        volumeMounts:

        - name: shared-storage

          mountPath: /mnt

      volumes:

      - name: shared-storage
        
        persistentVolumeClaim:
    
            claimName: shared-pvc
