apiVersion: apps/v1

kind: Deployment

metadata:

  name: data-processing

spec:

  replicas: 1

  selector:

    matchLabels:

      app: data-processing

  template:

    metadata:

      labels:

        app: data-processing

    spec:

      containers:

      - name: data-processing-container

        image: rhiann/dataprocessing:latest

        volumeMounts:

        - name: shared-pv

          mountPath: /mnt/data

      volumes:

      - name: shared-pv

        persistentVolumeClaim:

          claimName: shared-pvc